ci

diff --git a/.github/workflows/packages.yml b/.github/workflows/packages.yml
--- a/.github/workflows/packages.yml
+++ b/.github/workflows/packages.yml
@@ -31,10 +31,11 @@ jobs:
     strategy:
       matrix:
         target_arch: [aarch64, arm, i686, x86_64]
-        build_type: [cross, on_device]
+        build_type: [cross, native]
       fail-fast: false
     steps:
     - name: Setup arm and aarch64 CPU emulators
+      if: ${{ matrix.target_arch == 'aarch64' || matrix.target_arch == 'arm' }}
       uses: dbhi/qus/action@main
       with:
         targets: arm aarch64
@@ -206,8 +207,6 @@ jobs:
           fi
         fi
     - name: Build packages
-      env:
-        BUILD_TYPE: ${{ matrix.build_type }}
       run: |
         declare -a packages
         for repo_path in $(jq --raw-output 'del(.pkg_format) | keys | .[]' repo.json); do
@@ -221,7 +220,7 @@ jobs:
           if grep -qP "(^|\\s)${packages// /($|\\s)|(^|\\s)}($|\\s)" ./scripts/big-pkgs.list; then
             NDK=$ANDROID_NDK_LATEST_HOME ANDROID_HOME=$ANDROID_SDK_ROOT ./build-package.sh -I -a ${{ matrix.target_arch }} $packages
           else
-            if [ "$BUILD_TYPE" = "on_device" ]; then
+            if [ "${{ matrix.build_type }}" = "native" ]; then
               docker run -i --name termux-docker-${{ matrix.target_arch }} --unprivileged --volume $PWD:/data/data/com.termux/files/home/termux-packages \
                 --workdir /data/data/com.termux/files/home/termux-packages termux/termux-docker:${{ matrix.target_arch }} \
                 ./scripts/setup-termux.sh && ./build-package.sh -I -f $packages
@@ -324,15 +323,14 @@ jobs:
       with:
         path: ./
     - name: Download Termux APK
-      env:
-        ARCH: ${{ matrix.target_arch }}
       run: |
         TERMUX_APK_URL=$(curl -s https://api.github.com/repos/termux/termux-app/releases/latest | grep browser_download_url | sed -e 's|.*: ||' -e 's|"||g')
-        case "$ARCH" in
+        case "${{ matrix.target_arch }}" in
         aarch64) TERMUX_APK_URL=$(echo "$TERMUX_APK_URL" | grep arm64) ;;
         arm) TERMUX_APK_URL=$(echo "$TERMUX_APK_URL" | grep armeabi) ;;
         i686) TERMUX_APK_URL=$(echo "$TERMUX_APK_URL" | grep x86 | grep -v x86_64) ;;
         x86_64) TERMUX_APK_URL=$(echo "$TERMUX_APK_URL" | grep x86_64) ;;
+        *) echo "ERROR: $*" && exit 1 ;;
         esac
         echo "Downloading $TERMUX_APK_URL"
         curl -L $TERMUX_APK_URL -o termux-${{ matrix.target_arch }}.apk
