ci(packages): add Android Emulator for testing

diff --git a/.github/workflows/packages.yml b/.github/workflows/packages.yml
--- a/.github/workflows/packages.yml
+++ b/.github/workflows/packages.yml
@@ -210,7 +210,6 @@ jobs:
             cd ..
           fi
         fi
-
     - name: Lint packages
       run: |
         declare -a package_recipes=()
@@ -224,7 +223,6 @@ jobs:
         if [[ "${#package_recipes[@]}" -gt 0 ]]; then
           ./scripts/lint-packages.sh "${package_recipes[@]}"
         fi
-
     - name: Free additional disk space (if needed)
       if: ${{ steps.build-info.outputs.docker-build == 'false' && steps.build-info.outputs.skip-building != 'true' }}
       run: |
@@ -235,7 +233,6 @@ jobs:
         rm -f ${HOME}/lib/ndk-*.zip ${HOME}/lib/sdk-*.zip
         sudo apt install ninja-build
         ./scripts/free-space.sh
-
     - name: Build packages
       if: ${{ steps.build-info.outputs.skip-building != 'true' }}
       env:
@@ -264,7 +261,6 @@ jobs:
             ./scripts/run-docker.sh ./build-package.sh -I -C -a "${{ matrix.target_arch }}" "${packages[@]}"
           fi
         fi
-
     - name: Generate build artifacts
       if: always()
       run: |
@@ -461,3 +457,173 @@ jobs:
             fi
           fi
         done
+
+  on-device-test-no-build:
+    #if: false
+    permissions:
+      contents: read
+    strategy:
+      matrix:
+        # TODO QEMU2 Android emulator cant run ARM images on x86_64 host (ubuntu-*)
+        # TODO there is no prebuilt Android emulator for ARM host (ubuntu-*-arm)
+        # ARM emulation in x86_64 images errors on termux-bootstrap-second-stage.sh
+        # API 26 has broken Internet, adb input
+        # x86_64 API 27 google_apis is unavailable
+        # there is no i686 API 30+ image
+        target_arch: [i686, x86_64]
+        api: [24, 25, 26, 27, 28, 29, 30, 31, 32 ,33, 34, 35, 36]
+        image: [google_apis]
+        os: [ubuntu-24.04]
+        include:
+          - target_arch: i686
+            arch: x86
+          - target_arch: x86_64
+            arch: x86_64
+        exclude:
+          - target_arch: i686
+            api: 26
+          - target_arch: i686
+            api: 30
+          - target_arch: i686
+            api: 31
+          - target_arch: i686
+            api: 32
+          - target_arch: i686
+            api: 33
+          - target_arch: i686
+            api: 34
+          - target_arch: i686
+            api: 35
+          - target_arch: i686
+            api: 36
+          - target_arch: x86_64
+            api: 26
+          - target_arch: x86_64
+            api: 27
+
+      fail-fast: false
+    runs-on: ${{ matrix.os }}
+    steps:
+    - name: Clone repository
+      uses: actions/checkout@v4
+    - name: Enable KVM
+      run: |
+        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
+        sudo udevadm control --reload-rules
+        sudo udevadm trigger --name-match=kvm
+    - name: Download Termux APK (Debug)
+      run: |
+        TERMUX_APK_URL=$(curl --retry 3 -s https://api.github.com/repos/termux/termux-app/releases/latest | grep browser_download_url | sed -e 's|.*: ||' -e 's|"||g')
+        case "${{ matrix.target_arch }}" in
+        aarch64) TERMUX_APK_URL=$(echo "$TERMUX_APK_URL" | grep arm64) ;;
+        arm) TERMUX_APK_URL=$(echo "$TERMUX_APK_URL" | grep armeabi) ;;
+        i686) TERMUX_APK_URL=$(echo "$TERMUX_APK_URL" | grep x86 | grep -v x86_64) ;;
+        x86_64) TERMUX_APK_URL=$(echo "$TERMUX_APK_URL" | grep x86_64) ;;
+        *) echo "ERROR: $*" && exit 1 ;;
+        esac
+        echo "curl --retry 3 -L $TERMUX_APK_URL -o termux-${{ matrix.target_arch }}.apk"
+        curl --retry 3 -L $TERMUX_APK_URL -o termux-${{ matrix.target_arch }}.apk
+    - name: Disable console authentication
+      # https://developer.android.com/studio/run/emulator-console#console-session
+      run: |
+        > ~/.emulator_console_auth_token
+    - name: Test with Android Emulator
+      uses: reactivecircus/android-emulator-runner@v2
+      with:
+        api-level: ${{ matrix.api }} # 24-30
+        arch: ${{ matrix.arch }} # arm64-v8a, x86, x86_64
+        target: ${{ matrix.image }} # default, google_apis
+        cores: 4
+        ram-size: 2048M
+        force-avd-creation: false
+        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
+        enable-hw-keyboard: true
+        script: |
+          pwd
+          ls -l
+
+          for i in $(seq -w 1 100); do if adb wait-for-device shell test -f /sdcard/ok; then echo "=== quit logcat ==="; break; fi; echo "=== new logcat $i ==="; adb wait-for-device logcat >logcat${i}.txt; done &
+          # 180s = 3min, 6h = 360min = 120 * 3min
+          for i in $(seq -w 1 116); do if adb shell test -f /sdcard/ok; then echo "=== quit screenrecord ==="; break; fi; echo "=== new screenrecord $i ==="; adb shell screenrecord --verbose --time-limit 180 /sdcard/sr${i}.mp4; sync; adb pull /sdcard/sr${i}.mp4; adb shell rm /sdcard/sr${i}.mp4; done &
+
+          #./scripts/test-runner-ci.sh
+
+          tar -cf payload.tar.gz -C ../termux-packages .git repo.json scripts/properties.sh
+
+          adb install -g termux-${{ matrix.target_arch }}.apk
+          adb shell pm path com.termux
+          adb shell am start -n com.termux/com.termux.app.TermuxActivity
+          sleep 30
+          #adb shell pm grant com.termux android.permission.READ_EXTERNAL_STORAGE
+          #adb shell pm grant com.termux android.permission.WRITE_EXTERNAL_STORAGE
+          adb shell input text "termux-setup-storage%s\&\&%ssleep%s1"
+          adb shell input keyevent KEYCODE_ENTER
+          sleep 1
+
+          adb shell id
+          adb shell run-as com.termux id
+          adb shell input text "id\%s\|%stee%sid\.txt%s\&\&%ssleep%s1"
+          adb shell input keyevent KEYCODE_ENTER
+          sleep 1
+          adb shell 'run-as com.termux cat /data/data/com.termux/files/home/id.txt || true'
+
+          #adb push payload.tar.gz /sdcard/Download/payload.tar.gz
+          #adb shell ls -l /sdcard/Download
+          adb shell rm -fr /data/local/tmp/tmp
+          adb shell mkdir -p /data/local/tmp/tmp
+          adb push payload.tar.gz /data/local/tmp/tmp/payload.tar.gz
+          adb shell ls -l /data/local/tmp/tmp
+          adb shell run-as com.termux ls -l /data/local/tmp/tmp
+          adb shell input text "ls%s\-l%s\/sdcard\/Download%s\|%stee%sdownload\.txt%s\&\&%ssleep%s1"
+          adb shell input keyevent KEYCODE_ENTER
+          sleep 1
+          adb shell 'run-as com.termux cat /data/data/com.termux/files/home/download.txt || true'
+
+          adb shell run-as com.termux pwd
+          adb shell run-as com.termux ls -l
+          adb shell run-as com.termux ls -l /data/data/com.termux
+          adb shell run-as com.termux ls -l /data/data/com.termux/files
+          adb shell run-as com.termux ls -l /data/data/com.termux/files/home
+          adb shell 'run-as com.termux ls -l /data/data/com.termux/files/home/storage || true'
+          adb shell 'run-as com.termux ls -l /data/data/com.termux/files/home/storage/shared || true'
+          adb shell run-as com.termux ls -l /data/data/com.termux/files/usr
+
+          adb shell run-as com.termux mkdir -p /data/data/com.termux/files/home/termux-packages/scripts
+          #adb shell run-as com.termux ls -l /sdcard/Download
+          #adb shell 'run-as com.termux sh -c "mv -fv /sdcard/Download/payload.tar.gz /data/data/com.termux/files/home/termux-packages/payload.tar.gz || true"' # ignore chown error
+          adb shell 'run-as com.termux sh -c "cp -fv /data/local/tmp/tmp/payload.tar.gz /data/data/com.termux/files/home/termux-packages/payload.tar.gz || true"' # mv may error
+          adb shell run-as com.termux tar -xof /data/data/com.termux/files/home/termux-packages/payload.tar.gz -C /data/data/com.termux/files/home/termux-packages
+          exit
+
+          #adb shell input text "watch%sps%sax%s-H"
+          #adb shell input keyevent KEYCODE_ENTER
+          #sleep 1
+          adb shell run-as com.termux ps
+          adb shell run-as com.termux ls -l /data/data/com.termux/files/home/termux-packages/scripts
+          adb shell run-as com.termux env PATH=/data/data/com.termux/files/usr/bin pkg install xxd jq git -y
+          adb shell run-as com.termux ls -l /data/data/com.termux/files/home/termux-packages
+          adb shell run-as com.termux env PATH=/data/data/com.termux/files/usr/bin git -C /data/data/com.termux/files/home/termux-packages restore .
+          adb shell run-as com.termux ls -l /data/data/com.termux/files/home/termux-packages
+          adb shell "run-as com.termux env LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec-ld-preload.so PATH=/data/data/com.termux/files/usr/bin TMPDIR=/data/data/com.termux/files/usr/tmp bash -c 'pwd; ls -l; cd /data/data/com.termux/files/home/termux-packages; pwd; ls -l; ./scripts/lint-packages.sh | tee lint-packages.log'" || true
+
+          adb shell "run-as com.termux env LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec-ld-preload.so PATH=/data/data/com.termux/files/usr/bin TMPDIR=/data/data/com.termux/files/usr/tmp bash -c 'pwd; ls -l; cd /data/data/com.termux/files/home/termux-packages; sha256sum lint-packages.log'"
+
+          adb shell input text "cd%stermux\-packages"
+          adb shell input keyevent KEYCODE_ENTER
+          sleep 1
+          adb shell input text "\.\/scripts\/lint\-packages\.sh"
+          adb shell input keyevent KEYCODE_ENTER
+          sleep 1
+
+          adb shell touch /sdcard/ok
+
+          adb shell "while true; do if ! pgrep screenrecord >/dev/null; then pkill screenrecord; else break; fi; sleep 1; done"
+          kill $(ps ax | grep logcat | awk '{print $1}')
+    - name: Upload logs and videos
+      if: always()
+      uses: actions/upload-artifact@v4
+      with:
+        name: ondevicetestnobuild-${{ matrix.target_arch }}-${{ matrix.api }}-${{ matrix.image }}-${{ github.sha }}
+        path: |
+          logcat*.txt
+          sr*.mp4
